[2023-07-05 23:29:28,797] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:29:30,248] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:29:30,423] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:29:31,934] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:03,636] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:03,639] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:07,156] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:07] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:07,249] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:07] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:07,663] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:07] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:07,675] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:07] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:07,691] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:07] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:08,425] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:08] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:08,451] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:08] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:08,462] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:08,463] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:08,710] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:08] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:12,364] WARNING add_bebida() L52   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L52  
[2023-07-05 23:35:12,366] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:12] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 409 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:24,096] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:24] "DELETE /bebida/deletar?id=1&nome=Pink%20Drink HTTP/1.1" 200 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:29,743] WARNING add_bebida() L56   Erro ao adicionar uma nova bebida 'Pink Drink', Não foi possível salvar uma nova bebida no cardapio :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L56  
[2023-07-05 23:35:29,749] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:29] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 400 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:33,065] WARNING add_bebida() L52   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L52  
[2023-07-05 23:35:33,066] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:33] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 409 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:35:44,999] ERROR log_exception() L1449 Exception on /bebida/listas [GET] - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\app.py", line 97, in get_bebidas
    return apresenta_bebida(bebida), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 57, in apresenta_bebida
    result.append(apresenta_bebida(bebida))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 56, in apresenta_bebida
    for bebida in bebidas:
TypeError: 'Bebida' object is not iterable
[2023-07-05 23:35:45,014] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:35:45] "[35m[1mGET /bebida/listas HTTP/1.1[0m" 500 - - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:36:37,465] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:36:37,654] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Izabelle Rosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:03,248] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:03,262] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:16,299] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:57:16] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:16,339] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:57:16] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:16,587] INFO _log() L224  127.0.0.1 - - [05/Jul/2023 23:57:16] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-05 23:57:27,922] WARNING add_bebida() L52   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L52  
