[2023-07-05 23:58:34,870] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:30,393] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:30,395] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,228] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,430] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,447] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,459] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,810] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:36,844] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:36] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:00:46,277] WARNING add_bebida() L52   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L52  
[2023-07-06 00:00:46,278] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:00:46] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 409 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:01:43,296] WARNING add_bebida() L56   Erro ao adicionar uma nova bebida 'Chá verde', Não foi possível salvar uma nova bebida no cardapio :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L56  
[2023-07-06 00:01:43,297] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:01:43] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 400 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:23,911] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:23,916] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:29,610] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:29] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:29,646] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:29] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:29,923] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:29] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:29,936] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:29] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:29,949] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:29] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:30,649] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:30] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:30,679] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:30] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:30,686] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:30] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:30,687] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:30] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:30,898] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:30] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:02:43,531] WARNING add_bebida() L56   Erro ao adicionar uma nova bebida 'Pink Drink', Não foi possível salvar uma nova bebida no cardapio :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L56  
[2023-07-06 00:02:43,532] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:02:43] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 400 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:03:19,033] WARNING add_bebida() L56   Erro ao adicionar uma nova bebida 'Chá verde', Não foi possível salvar uma nova bebida no cardapio :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L56  
[2023-07-06 00:03:19,034] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:03:19] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 400 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:03:31,037] ERROR log_exception() L1449 Exception on /bebida/listas [GET] - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\app.py", line 97, in get_bebidas
    return apresenta_bebida(bebida), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 57, in apresenta_bebida
    result.append(apresenta_bebida(bebida))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 56, in apresenta_bebida
    for bebida in bebidas:
TypeError: 'Bebida' object is not iterable
[2023-07-06 00:03:31,044] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:03:31] "[35m[1mGET /bebida/listas HTTP/1.1[0m" 500 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:04:29,442] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:04:29,447] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:04:32,863] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:04:32] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:04:32,895] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:04:32] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:47,253] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
